export {default as Login} from './Login/Login'
export {default as Home} from './Home/Home'
export {default as SignUp} from './SignUp/SignUp'
export {default as Activate} from './Activate/Activate'
export {default as Landing} from './Landing/Landing'
export {default as ResetPassword} from './ResetPassword/ResetPassword'
export {default as ResetPasswordConfirm} from './ResetPassword/ResetPasswordConfirm'
export {default as Restaurants} from './Restaurants'