# Generated by Django 4.1.3 on 2022-11-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_price', models.IntegerField(default=0)),
                ('prefer_philanthropic', models.BooleanField(default=False)),
                ('prefer_env_conscious', models.BooleanField(default=False)),
                ('prefer_minority', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('favorites', models.JSONField(blank=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
