# Generated by Django 4.1.3 on 2022-11-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_id_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='favorites',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='prefer_env_conscious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='prefer_minority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='prefer_philanthropic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='prefer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
