# Generated by Django 4.1.3 on 2022-11-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_dark_mode_useraccount_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='prefer_price',
            field=models.IntegerField(default=1),
        ),
    ]
