# Generated by Django 4.1.3 on 2022-11-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_restaurant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
