# Generated by Django 4.1.3 on 2022-11-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_favorites_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='num_chosen',
        ),
    ]
