# Generated by Django 4.1.3 on 2022-11-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_favorites_num_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='food_category',
            field=models.IntegerField(default=0),
        ),
    ]
